##
## EPITECH PROJECT, 2021
## Makefile
## File description:
## Makefile
##

all:
	@$(MAKE) --no-print-directory -C ./Pacman
	@$(MAKE) --no-print-directory -C ./Nibbler

clean:
	@$(MAKE) --no-print-directory -C ./Pacman clean
	@$(MAKE) --no-print-directory -C ./Nibbler clean

fclean:
	@$(MAKE) --no-print-directory -C ./Pacman fclean
	@$(MAKE) --no-print-directory -C ./Nibbler fclean

re:
	@$(MAKE) --no-print-directory -C ./Pacman re
	@$(MAKE) --no-print-directory -C ./Nibbler re

print-%  : ; @echo $* = $($*)
