version: "3"
services:
  react:
    container_name: "React"
    build: ./web
    ports:
      - "8081:3000"
    depends_on:
      - dotnet
      - mobile
    volumes:
      - mobile-app:/apk

  dotnet:
    container_name: "Dotnet"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mongodb
    links:
      - mongodb

  mobile:
    container_name: "Flutter"
    build: ./mobile
    env_file:
      - env/mobile.env
    volumes:
      - mobile-app:/mobileapp

  mongodb:
    image: mongo
    container_name: "MongoDB"
    env_file:
      - ./env/mongodb.env
    ports:
      - "27017:27017"
    restart: unless-stopped

  dataseeder:
    container_name: "DataSeeder"
    build:
      context: ./server
      dockerfile: ./Dockerfile.dataseeder
    depends_on:
      - mongodb
    links:
      - mongodb

  worker:
    container_name: "Worker"
    build:
      context: ./server/Worker
      dockerfile: ./Dockerfile
    depends_on:
      - dotnet
    links:
      - dotnet

volumes:
  mobile-app:

